config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'forums#index'

  resources :comments
  resources :topics
  resources :categories
  devise_for :users, controllers: { sessions: "devise_ex/sessions",
                                    registrations: "devise_ex/registrations" }

  resource :forums do
    get 'index'
    get 'admin'
    get 'home'
    post 'search'
    get 'search'
    get 'page/:page', :action => :index, :on => :collection
  end

  namespace :admin do
    resources :comments, :only => [:index, :show, :edit, :update, :destroy]
    resources :categories do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :topics do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :users, :only => [:index, :show, :edit]
    post 'users/:id' => 'users#update'
    patch 'users/:id' => 'users#update'

  end

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_date_params, only: [:search]
  before_action :set_status_params, only: [:search]
  def index
    unless current_user.try(:admin?)
      redirect_to "/forums/home"
    end
  end
  def home
    @categories = Category.where.not(status: Category.statuses[:deleted]).order("created_at asc")

    late = Time.now - 3.day
    @created_topics = Topic.where("created_at >= ?", late)
                           .where.not("status = ?",Topic.statuses[:deleted])
                           .order('created_at desc')

    @wrote_topics = Topic.joins(:comments)
                         .select("topics.*")
                         .where("comments.created_at >= ?", late)
                         .where.not("comments.status = ?", Comment.statuses[:deleted])
                         .where.not("topics.status = ?", Topic.statuses[:deleted])
                         .uniq
  end
  def search
    word =
      if params["word"]
        params["word"][0]
      else
        ""
      end
    topic_search={title_or_value_cont: word}
    comment_search={value_cont: word}
    @view_topics = params[:topic]
    @view_comments = params[:comment]
    @view_users = params[:user]

    if @view_topics.nil? and @view_comments.nil? and @view_users.nil?
      @view_topics = @view_comments = @view_users = true
    end
    topic_search.merge! @date_params
    comment_search.merge! @date_params
    if current_user.try(:admin?) and @view_users
      if @category_id.blank?
        @category_ids = Category.select(:id).where("status in (?)",@category_statuses)
      else
        @category_ids = [@category_id]
      end

      @topics = Topic.search(topic_search).result.where("status in (?)",@topic_statuses).where("category_id in (?)",@category_ids).page params[:page] if @view_topics
      @topic_ids = Topic.select(:id).where("category_id in (?)",@category_ids)
      @comments = Comment.search(comment_search).result.where("status in (?)",@comment_statuses).where("topic_id in (?)",@topic_ids).page params[:page] if @view_comments

      user_search={email_or_username_cont: word}
      user_search.merge! @date_params
      @users = User.search(user_search).result.where("status in (?)",@user_statuses).page params[:page]
    else
      if @category_id.blank?
        @category_ids = Category.select(:id).where.not(status: Category.statuses[:deleted])
      else
        @category_ids = [@category_id]
      end
      @topics = Topic.search(topic_search).result.where.not(status: Topic.statuses[:deleted]).where("category_id in (?)",@category_ids).page params[:page] if @view_topics
      @topic_ids = Topic.select(:id).where("category_id in (?)",@category_ids).where.not(status: Topic.statuses[:deleted])
      @comments = Comment.search(comment_search).result.where.not(status: Comment.statuses[:deleted]).where("topic_id in (?)",@topic_ids).page params[:page] if @view_comments
    end
  end
  def admin
  end

  private
  def set_status_params
    @category_statuses = []
    @topic_statuses = []
    @comment_statuses = []
    @user_statuses = []
    @category_id = 
      if params["category"]
        params["category"]["id"]
      else
        ""
      end
    if params["category_statuses"]
      params["category_statuses"].each_key do |s|
        @category_statuses << Category.statuses[s]
      end
    end
    if params["topic_statuses"]
      params["topic_statuses"].each_key do |s|
        @topic_statuses << Topic.statuses[s]
      end
    end
    if params["comment_statuses"]
      params["comment_statuses"].each_key do |s|
        @comment_statuses << Comment.statuses[s]
      end
    end
    if params["user_statuses"]
      params["user_statuses"].each_key do |s|
        @user_statuses << User.statuses[s]
      end
    end
    if @category_statuses.blank? and @topic_statuses.blank? and @comment_statuses.blank? and @user_statuses.blank?

      @category_statuses = Category.statuses.values
      @topic_statuses = Topic.statuses.values
      @comment_statuses = Comment.statuses.values
      @user_statuses = User.statuses.values
    end
  end
  def set_date_params
    @date_params={}
    if params["between"].present?
      case params["between"]["datetime"]
      when "appoint"
        year,month,day = params["created_at_gteq"][0].split("/")
        @date_params[:created_at_gteq] = 
          begin
            Time.new(year,month,day,0,0,0)
          rescue
            Time.new - 100.year
          end
        year,month,day = params["created_at_lteq"][0].split("/")
        @date_params[:created_at_lteq] =
          begin
            Time.new(year,month,day,24,0,0)
          rescue
            Time.new
          end
      when "1hour"
        @date_params[:created_at_gteq] = Time.now - 1.hour
        @date_params[:created_at_lteq] = Time.now
      when "24hours"
        @date_params[:created_at_gteq] = Time.now - 1.day
        @date_params[:created_at_lteq] = Time.now
      when "1week"
        @date_params[:created_at_gteq] = Time.now - 1.week
        @date_params[:created_at_lteq] = Time.now
      when "1month"
        @date_params[:created_at_gteq] = Time.now - 1.month
        @date_params[:created_at_lteq] = Time.now
      when "1year"
        @date_params[:created_at_gteq] = Time.now - 1.year
        @date_params[:created_at_lteq] = Time.now
      end
    end
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/admin.html.erb
メニュー
<ul>
  <li><%= link_to 'カテゴリ',controller: 'categories',action: 'index' %></li>
  <li><%= link_to 'トピック',controller: 'topics',action: 'index' %></li>
  <li><%= link_to 'コメント',controller: 'comments',action: 'index' %></li>
  <li><%= link_to 'ユーザ',controller: 'users',action: 'index' %></li>
</ul>

app/views/forums/home.html.erb
<% breadcrumb :root %>
<div style="display: inline;">
  <% @categories.each do |category| %>
    <div class="col-xs-12 col-sm-3 col-md-2" style="margin: 10px 10px 10px 10px">
      <%= link_to category do %>
        <div style="text-align: center">
          <% if category.image? %>
            <%= image_tag category.image.thumb.url, class: "img-responsive center-block", width: "50px", height: "50px"%>
          <% else %>
            <%= image_tag "/category-default.png", class: "img-responsive center-block", width: "50px", height: "50px"%>
          <% end %>
          <%= category.title %>
        </div><!-- end panel-body -->
      <% end %>
    </div><!-- end panel -->
  <% end %>
</div>

<div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="text-center">
    <h3>新着情報</h3>
  </div>
  <div class="col-sm-5 col-sm-offset-1">
    <div class="text-center"><strong>新規トピック</strong></div>
    <div style="height:200px;overflow:scroll;">
      <table class="table table-bordered table-striped">
        <tbody>
          <% @created_topics.each do |ct| %>
            <tr>
              <td class="col-sm-6 col-xs-5"><%= ct.created_at %></td>
              <td class="long-text col-sm-6 col-xs-7"><%= link_to ct.title, topic_path(ct) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br />
  </div><!-- col -->
  <div class="col-sm-5">
    <div class="text-center"><strong>新規コメント</strong></div>
    <div style="height:200px;overflow:scroll;">
      <table class="table table-bordered table-striped">
        <tbody>
          <% @wrote_topics.each do |wt| %>
            <tr>
              <td class="col-sm-6 col-xs-5"><%= wt.created_at %></td>
              <td class="long-text col-sm-6 col-xs-7"><%= link_to wt.title, topic_path(wt) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!-- col -->
  </div>
</div>

app/views/forums/index.html.erb
<% breadcrumb :admin_root %>
<div class="container">
  <ul>
    <li><%= link_to 'カテゴリ', admin_categories_path %></li>
    <li><%= link_to 'トピック', admin_topics_path %></li>
    <li><%= link_to 'コメント', admin_comments_path %></li>
    <li><%= link_to 'ユーザ', admin_users_path %></li>
  </ul>
</div>

app/views/forums/search.html.erb
<% breadcrumb :search %>

<% if @view_topics %>
  <strong>トピック</strong>
  <% if @topics.blank? %>
    <strong>該当なし</strong>
  <% end %>
  <table class="table table-striped">
    <tbody>
      <% @topics.each do |t| %>
        <tr>
          <td>
            <%= link_to t do %>
              <div>
                <strong><%= t.title %></strong>
              </div>
              <div>
                <label class="long-text"><%= strip_tags(t.value) %></label>
              </div>
            <% end %>
          </td>
          <% if current_user.try(:admin?) %>
            <td class="col-xs-1">
              <%= link_to edit_admin_topic_path(t) do %>
                <span class=" btn btn-success glyphicon glyphicon-edit"></span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center"><%= paginate @topics %></div>
<% end %>
<% if @view_comments %>
  <strong>コメント</strong>
  <% if @comments.blank? %>
    <strong>該当なし</strong>
  <% end %>
  <table class="table table-striped">
    <tbody>
      <% @comments.each do |c| %>
        <tr>
          <td>
            <%= link_to c.topic do %>
              <div>
                <label class="long-text"><%= strip_tags(c.value) %></label>
              </div>
            <% end %>
          </td>
          <% if current_user.try(:admin?) %>
            <td class="col-xs-1">
              <%= link_to edit_admin_comment_path(c) do %>
                <span class=" btn btn-success glyphicon glyphicon-edit"></span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center"><%= paginate @comments %></div>
<% end %>
<% if @view_users and current_user.try(:admin?) %>
  <strong>ユーザ</strong>
  <% if @users.blank? %>
    <strong>該当なし</strong>
  <% end %>
  <table class="table table-striped">
    <tbody>
      <% @users.each do |u| %>
        <tr>
          <td>
            <%= link_to admin_user_path(u) do %>
              <div>
                <label class="long-text"><%= u.username %></label>
              </div>
            <% end %>
          </td>

          <td>
            <%= link_to admin_user_path(u) do %>
              <div>
                <label class="long-text"><%= u.email %></label>
              </div>
            <% end %>
          </td>
          <% if current_user.try(:admin?) %>
            <td class="col-xs-1">
              <%= link_to edit_admin_user_path(u) do %>
                <span class=" btn btn-success glyphicon glyphicon-edit"></span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center"><%= paginate @users %></div>
<% end %>