config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'forums#index'

  resources :comments
  resources :topics
  resources :categories
  devise_for :users, controllers: { sessions: "devise_ex/sessions",
                                    registrations: "devise_ex/registrations" }

  resource :forums do
    get 'index'
    get 'admin'
    get 'home'
    post 'search'
    get 'search'
    get 'page/:page', :action => :index, :on => :collection
  end

  namespace :admin do
    resources :comments, :only => [:index, :show, :edit, :update, :destroy]
    resources :categories do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :topics do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :users, :only => [:index, :show, :edit]
    post 'users/:id' => 'users#update'
    patch 'users/:id' => 'users#update'

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  mount_uploader :image, ImageUploader
  enum status: [:active, :locked, :deleted]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/admin/users_controller.rb
# coding: utf-8
class Admin::UsersController < ApplicationController
  before_action :admin_required
  before_action :set_user, only: [:show, :edit, :update]
  def index
    @users = User.all
  end

  def show
    @topics = Topic.where(user_id: @user.id)
    @comments = Comment.where(user_id: @user.id)
  end

  def edit
  end

  def update
    if user_params[:password].present?
      @user.password = user_params[:password]
      @user.password_confirmation = user_params[:password]
    end
    @user.email = user_params[:email]
    @user.username = user_params[:username]
    @user.status = user_params[:status]
    @user.admin = user_params[:admin]
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'ユーザ情報を変更しました。' }
      else
        format.html { render :edit, notice: '変更できませんでした'}
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :username, :password, :status, :admin)
    end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_action :admin_required
  before_action :set_user, only: [:show, :edit, :update]
  def index
    @users = User.all
  end

  def show
    @topics = Topic.where(user_id: @user.id)
    @comments = Comment.where(user_id: @user.id)
  end

  def edit
  end

  def update
    if user_params[:password].present?
      @user.password = user_params[:password]
      @user.password_confirmation = user_params[:password]
    end
    @user.email = user_params[:email]
    @user.username = user_params[:username]
    @user.status = user_params[:status]
    @user.admin = user_params[:admin]
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'ユーザ情報を変更しました。' }
      else
        format.html { render :edit, notice: '変更できませんでした'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :username, :password, :status, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<%= form_for(@user) do |f| %>
  <div class="form-group">
    <label><%= f.label :username %></label>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <label><%= f.label :email %></label>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label><%= f.label :password %></label>
    <%= f.text_field :password, autocomplete: "off", placeholder: "8文字以上半角", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>ステータス</label>
    <% User.statuses.each_key do |s|%>
      <div class="radio">
        <label>
          <input type="radio" value="option1" checked="">
          <% check = @user.status == s ? "checked" : ""%>
          <%= f.radio_button :status, s, checked: check %><%= I18n.t "user_status.#{s}" %>
        </label>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <label>権限</label>
    <div class="checkbox">
      <label><%= f.check_box :admin %><%= I18n.t "admin" %></label>
    </div>
  </div>

  <div class="form-group">
    <div class="pull-right">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<% breadcrumb :index_user %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>名前</th>
      <th>メール</th>
      <th>ステータス</th>
      <th>権限</th>
      <th class="col-xs-1"></th>
    </tr>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
      <td><%= user.email %></td>
      <td><%= I18n.t("user_status.#{user.status}") %></td>
      <td><%= "管理者" if user.admin? %></td>
      <td class="col-xs-1"><%= link_to edit_user_path(user) do %>
          <span class=" btn btn-success glyphicon glyphicon-edit"></span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<div class="container">
  <div class="row center-block col-xs-12 col-sm-12 col-md-12 col-lg-12">
    名前: <%= link_to @user.username, edit_user_path(@user) %><br>
    メール: <%= @user.email %><br>
    <h3>トピック履歴</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>トピック</th>
          <th>詳細</th>
          <th>作成日</th>
          <th>更新日</th>
          <th>関連カテゴリ</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @topics.each do |t|%>
          <tr>
            <td class="long-text" title="<%= t.title %>"><%= link_to t.title, t %></td>
            <td class="long-text" title="<%= t.value %>"><%= t.value %></td>
            <td class="long-test"><%= t.created_at %></td>
            <td class="long-test"><%= t.updated_at %></td>
            <td class="long-test"><%= link_to t.category.title, t.category %></td>
            <td class="col-xs-1"><%= link_to edit_topic_path(t) do %>
              <span class=" btn btn-success glyphicon glyphicon-edit"></span>
            <% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h3>コメント履歴</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>コメント</th>
          <th>画像</th>
          <th>作成日</th>
          <th>関連トピック</th>
          <th>関連カテゴリ</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |c|%>
          <tr>
            <td class="long-text" title="<%= c.value %>"><%= c.value %></td>
            <td>
              <% if c.image.url.present? %>
                <%= link_to c.image.url do %>
                  <%= image_tag c.image.thumb.url %>
                <% end %>
              <% else %>
                なし
              <% end %>
            </td>
            <td class="long-text"><%= c.created_at %></td>
            <td class="long-text"><%= link_to c.topic.title, c.topic %></td>
            <td class="long-text"><%= link_to c.topic.category.title, c.topic.category %></td>
            <td class="col-xs-1"><%= link_to edit_comment_path(c) do %>
              <span class=" btn btn-success glyphicon glyphicon-edit"></span>
            <% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>