config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'forums#index'

  resources :comments
  resources :topics
  resources :categories
  devise_for :users, controllers: { sessions: "devise_ex/sessions",
                                    registrations: "devise_ex/registrations" }

  resource :forums do
    get 'index'
    get 'admin'
    get 'home'
    post 'search'
    get 'search'
    get 'page/:page', :action => :index, :on => :collection
  end

  namespace :admin do
    resources :comments, :only => [:index, :show, :edit, :update, :destroy]
    resources :categories do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :topics do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :users, :only => [:index, :show, :edit]
    post 'users/:id' => 'users#update'
    patch 'users/:id' => 'users#update'

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics
  mount_uploader :image, ImageUploader
  enum status: [:active, :deleted]
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @column = params[:column].nil? ? :title : params[:column]
    @order = params[:order] == "asc" ? 'desc': 'asc'
    @categories = Category.all.order("#{@column} #{@order}").page params[:page]
  end

  def show
    if @category.deleted?
      msg = "カテゴリが削除されています"
      if current_user.try(:admin)
        flash[:notice] = msg
      else
        render text: msg
      end
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: '新しいカテゴリを作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.status = Category.statuses[:deleted]
    if @category.save
      respond_to do |format|
        format.html { redirect_to categories_url, notice: '関連するトピック、コメントは表示されなくなりました。' }
      end
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title, :image, :status, :image_cache, :remove_image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def show
    if @category.deleted?
      msg = "カテゴリが削除されています"
      if current_user.try(:admin)
        flash[:notice] = msg
      else
        render text: msg
      end
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<div class="container">
  <%= form_for([:admin,@category], class: "form-horizontal") do |f| %>
    <div class="form-group">
      <div class="col-xs-12 col-sm-offset-2 col-sm-10">
        <label class="col-xs-12 col-sm-2 control-label">タイトル</label>
        <div class="col-xs-12 col-sm-6">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-xs-12 col-sm-offset-2 col-sm-10">
        <label class="control-label col-xs-12 col-sm-2">画像</label>
        <div class="col-xs-12 col-sm-6">
          <div class="btn" onclick="document.getElementById('category_image').click()">
            <img src="<%= @category.image.url %>" id="preview" width="50px">
          </div> <div hidden="hidden" onchange="$('#preview').hide();reader=new FileReader();file=document.getElementById('category_image');f=file.files;reader.readAsDataURL(f[0]);reader.onload =(function(){$('#preview').show();$('#preview').attr('src',reader.result);});"><%= f.file_field :image %></div>
          <% if @category.image? %>
            <label>
              <%= f.check_box :remove_image %>画像削除
            </label>
          <% end %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
    </div>
    <% if @category.persisted? %>
      <div class="form-group">
        <div class="col-xs-12 col-sm-offset-2 col-sm-10">
          <label class="control-label col-xs-12 col-sm-2">ステータス</label>
          <div class="col-xs-12 col-sm-6">
            <% Category.statuses.each_key do |s|%>
              <div class="radio">
                <label>
                  <% check = @category.status == s ? "checked" : "" %>
                  <%= f.radio_button :status, s, checked: check %><%= I18n.t("category_status.#{s}") %>
                </label>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <div class="row col-xs-12 col-sm-offset-2 col-sm-8">
        <div class="pull-right">
          <%= f.submit class: "btn btn-primary"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<% breadcrumb :index_category, %>
<%= render 'form' %>

app/views/admin/categories/index.html.erb
<% breadcrumb :index_category %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= link_to 'タイトル', controller: 'categories', action: 'index', page: 1, order: @order, column: 'title' %></th>
      <th class="col-xs-2">画像</th>
      <th class="col-xs-2">ステータス</th>
      <th class="col-xs-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td class="long-text"><%= link_to category.title, category %></td>
        <td >
          <% if category.image.present? %>
            <%= link_to category.image.url, 'data-lightbox' => category.image.url do %>
              <%= image_tag category.image.thumb.url,class: "img-responsive center-block" %>
            <% end %>
          <% else %>
            なし
          <% end %>
        </td>
        <td><%= I18n.t("category_status.#{category.status}") %></td>
        <td class="col-xs-1">
          <%= link_to edit_admin_category_path(category) do %>
            <span class=" btn btn-success glyphicon glyphicon-edit"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pull-right">
  <%= link_to new_admin_category_path, class: "btn btn-primary" do %>
    <span class="glyphicon glyphicon-plus"></span>
  <% end %>
</div>
<div class="text-center"><%= paginate @categories %></div>

app/views/admin/categories/new.html.erb
<% breadcrumb :new_category, %>
<%= render 'form' %>