config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'forums#index'

  resources :comments
  resources :topics
  resources :categories
  devise_for :users, controllers: { sessions: "devise_ex/sessions",
                                    registrations: "devise_ex/registrations" }

  resource :forums do
    get 'index'
    get 'admin'
    get 'home'
    post 'search'
    get 'search'
    get 'page/:page', :action => :index, :on => :collection
  end

  namespace :admin do
    resources :comments, :only => [:index, :show, :edit, :update, :destroy]
    resources :categories do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :topics do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :users, :only => [:index, :show, :edit]
    post 'users/:id' => 'users#update'
    patch 'users/:id' => 'users#update'

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics
  mount_uploader :image, ImageUploader
  enum status: [:active, :deleted]
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @column = params[:column].nil? ? :title : params[:column]
    @order = params[:order] == "asc" ? 'desc': 'asc'
    @categories = Category.all.order("#{@column} #{@order}").page params[:page]
  end

  def show
    if @category.deleted?
      msg = "カテゴリが削除されています"
      if current_user.try(:admin)
        flash[:notice] = msg
      else
        render text: msg
      end
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: '新しいカテゴリを作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.status = Category.statuses[:deleted]
    if @category.save
      respond_to do |format|
        format.html { redirect_to categories_url, notice: '関連するトピック、コメントは表示されなくなりました。' }
      end
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title, :image, :status, :image_cache, :remove_image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def show
    if @category.deleted?
      msg = "カテゴリが削除されています"
      if current_user.try(:admin)
        flash[:notice] = msg
      else
        render text: msg
      end
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% breadcrumb :index_category %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= link_to 'タイトル', controller: 'categories', action: 'index', page: 1, order: @order, column: 'title' %></th>
      <th class="col-xs-2">画像</th>
      <th class="col-xs-2">ステータス</th>
      <th class="col-xs-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td class="long-text"><%= link_to category.title, category %></td>
        <td >
          <% if category.image.present? %>
            <%= link_to category.image.url do %>
              <%= image_tag category.image.thumb.url %>
            <% end %>
          <% else %>
            なし
          <% end %>
        </td>
        <td><%= I18n.t("category_status.#{category.status}") %></td>
        <td class="col-xs-1">
          <%= link_to edit_category_path(category) do %>
            <span class=" btn btn-success glyphicon glyphicon-edit"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pull-right">
  <%= link_to new_category_path, class: "btn btn-primary" do %>
    <span class="glyphicon glyphicon-plus"></span>
  <% end %>
</div>
<div class="text-center"><%= paginate @categories %></div>

app/views/categories/show.html.erb
<% breadcrumb :category, @category %>
<table class="table table-striped">
  <tbody>
    <% @category.topics.select{|t| !t.deleted?}.sort{|a,b|b.updated_at <=> a.updated_at}.each do |t| %>
      <tr>
        <td>
          <div class="col-xs-1">
            <% if t.user.image? %>
              <%= image_tag t.user.image.thumb.url, class: "img-circle", style: "height: 30px;width: 30px;" %>
            <% else %>
              <%= image_tag "/avatar-default.png", class: "img-circle", style: "height: 30px;width: 30px;" %>
            <% end %>
          </div>
          <div class="col-xs-7">
            <%= link_to t do %>
              <div>
                <strong><%= t.title %></strong>
              </div>
            <% end %>
            <div>
              <label class="long-text"><%= strip_tags(t.value) %></label>
            </div>
          </div >
          <div class="col-xs-3">
            <label class="long-text" style="font-size: xx-small;">
              作成者:<%= t.user.username %>
          </label>
          <label class="long-text" style="font-size: xx-small;">
            <%= t.comments.select{|c| !c.deleted?}.count %>件のコメント
          </label>
          <label class="long-text" style="font-size: xx-small;">
            最終更新:<%= t.updated_at %>
        </label>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user %>
  <div class="pull-right">
    <%= link_to new_topic_path(category_id: @category.id), class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-plus"></span>
    <% end %>
  </div>
<% end %>